[project]
name = "accounting_sh"
version = ""
description = "Accounting API"
authors = [{"name" = "STAN-TAB CORP. LTD", email="support@stantabcorp.com"}]
license = { file = "LICENSE" }
readme = "README.md"
keywords = ["OpenAPI", "Accounting API"]
requires-python = ">=3.10"

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Financial and Insurance Industry",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Office/Business",
    "Topic :: Office/Business :: Financial",
    "Topic :: Office/Business :: Financial :: Accounting",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "requests>=2.34.2,<3",
    "urllib3>=2.8.0,<3",
    "idna>=3.20,<4",
    "certifi>=2026.7.22",
    "typing-extensions>=4.16.0,<5"
]

[project.urls]
Homepage = "https://accounting.sh"
Repository = "https://github.com/accounting-sh/python_sdk.git"
Issues = "https://github.com/accounting-sh/python_sdk/issues"

[build-system]
requires = ["setuptools>=84.0.0,<85"]
build-backend = "setuptools.build_meta"
